import { useEffect, useMemo, useState } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { supabase } from '@/lib/supabase';
import { syncGoogleSheets } from '@/lib/data';
import type { Attendance, DailyReport, Employee } from '@/lib/types';

type Summary=Employee&{hadir:number;izin:number;sakit:number;cuti:number;dinas:number;tanpa:number;total:number};
type ResetRequest={id:string;requested_at:string;login_code:string};
const MONTHS=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
export default function Admin(){
 const [allowed,setAllowed]=useState<boolean|null>(null);const [month,setMonth]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}).slice(0,7));const [yearOpen,setYearOpen]=useState(false);const [monthOpen,setMonthOpen]=useState(false);const [employees,setEmployees]=useState<Employee[]>([]);const [attendance,setAttendance]=useState<Attendance[]>([]);const [reports,setReports]=useState<DailyReport[]>([]);const [workdays,setWorkdays]=useState<string[]>([]);const [resets,setResets]=useState<ResetRequest[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const selectedYear=month.slice(0,4);const selectedMonth=Number(month.slice(5,7));const jakartaYear=Number(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}).slice(0,4));const years=Array.from({length:jakartaYear-2024},(_,index)=>String(2025+index));
 const chooseYear=(year:string)=>{setMonth(`${year}-${String(selectedMonth).padStart(2,'0')}`);setYearOpen(false)};
 const chooseMonth=(monthNumber:number)=>{setMonth(`${selectedYear}-${String(monthNumber).padStart(2,'0')}`);setMonthOpen(false)};
 const closeDropdowns=()=>{setYearOpen(false);setMonthOpen(false)};
 const loadResets=async()=>{const{data,error}=await supabase.from('password_reset_requests').select('id,requested_at,login_code').eq('status','pending').order('requested_at');if(error)throw error;setResets((data??[]) as ResetRequest[])};
 const approveReset=async(id:string)=>{setBusy(true);setMessage('');try{const{data,error}=await supabase.functions.invoke('password-reset',{body:{action:'approve',requestId:id}});if(error||!data?.ok)throw new Error(data?.error);setMessage(`RESET BERHASIL — ${data.fullName} — kode: ${data.employeeCode} — password sementara: ${data.temporaryPassword}`);await loadResets()}catch(error){setMessage(error instanceof Error?error.message:'Reset password belum berhasil.')}finally{setBusy(false)}};
 const dismissReset=async(id:string)=>{setBusy(true);setMessage('');try{const{data,error}=await supabase.functions.invoke('password-reset',{body:{action:'dismiss',requestId:id}});if(error||!data?.ok)throw new Error(data?.error);setMessage('Permintaan reset berhasil diabaikan.');await loadResets()}catch(error){setMessage(error instanceof Error?error.message:'Permintaan reset belum dapat diabaikan.')}finally{setBusy(false)}};
 const sync=async()=>{closeDropdowns();setBusy(true);setMessage('');try{const result=await syncGoogleSheets(month);setMessage(`Spreadsheet berhasil disinkronkan untuk ${result.month}.`)}catch(error){setMessage(error instanceof Error?error.message:'Sinkronisasi gagal.')}finally{setBusy(false)}};
 const printAllMonthlyRecap=()=>{
  closeDropdowns();
  if(!/^\d{4}-\d{2}$/.test(month)||!employees.length){setMessage('Tampilkan data bulan yang dipilih terlebih dahulu.');return}
  const [yearText,monthText]=month.split('-');const year=Number(yearText);const monthIndex=Number(monthText)-1;const days=new Date(year,monthIndex+1,0).getDate();
  const monthLabel=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(year,monthIndex,1));
  const attendanceByEmployeeDate=new Map(attendance.map(row=>[`${row.employee_id}|${row.attendance_date}`,row]));
  const dayHeaders=Array.from({length:days},(_,index)=>{const day=index+1;const sunday=new Date(year,monthIndex,day).getDay()===0;return `<th class="${sunday?'sunday':''}">${day}</th>`}).join('');
  const rows=employees.map((employee,index)=>{
   const cells=Array.from({length:days},(_,dayIndex)=>{const day=dayIndex+1;const sunday=new Date(year,monthIndex,day).getDay()===0;if(sunday)return '<td class="sunday">Minggu</td>';const dateKey=`${month}-${String(day).padStart(2,'0')}`;const row=attendanceByEmployeeDate.get(`${employee.id}|${dateKey}`);const checkIn=row?.check_in?.slice(0,5).replace(':','.')??'-';const checkOut=row?.check_out?.slice(0,5).replace(':','.')??'-';return `<td><span>${checkIn}</span><span>${checkOut}</span></td>`}).join('');
   return `<tr><td class="number">${index+1}</td><td class="employee">${escapeHtml(employee.full_name)}</td>${cells}</tr>`;
  }).join('');
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>Rekap Absensi ${monthLabel}</title><style>@page{size:A3 landscape;margin:8mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111;margin:0}h1{text-align:center;text-transform:uppercase;font-size:18px;margin:0 0 4px}h2{text-align:center;text-transform:uppercase;font-size:15px;margin:0 0 14px}table{border-collapse:collapse;width:100%;table-layout:fixed;font-size:7px}th,td{border:1px solid #333;padding:3px 1px;text-align:center;vertical-align:middle}th{background:#dfe9e2;font-weight:700}.number{width:22px}.employee{width:145px;text-align:left;font-weight:600}.sunday{background:#f6d5d5;font-weight:700;color:#9b1c1c}td span{display:block;white-space:nowrap}td span+span{border-top:1px solid #bbb;margin-top:2px;padding-top:2px}</style></head><body><h1>Rekap Absensi PPPK Paruh Waktu</h1><h2>SDN Kalibaru 3 · ${escapeHtml(monthLabel)}</h2><table><thead><tr><th class="number">No</th><th class="employee">Nama Pegawai</th>${dayHeaders}</tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`;
  const popup=window.open('','_blank');if(!popup){setMessage('Jendela cetak diblokir browser. Izinkan pop-up lalu coba lagi.');return}popup.document.open();popup.document.write(html);popup.document.close();
 };
 const load=async()=>{closeDropdowns();setBusy(true);setMessage('');try{const{data:user}=await supabase.auth.getUser();const isAdmin=user.user?.app_metadata?.role==='admin';setAllowed(isAdmin);if(!isAdmin)return;
   const from=month+'-01';const last=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate();const to=month+'-'+String(last).padStart(2,'0');
   const[e,a,r,c]=await Promise.all([
    supabase.from('employees').select('id,employee_code,full_name,position,ni_pppk').eq('is_active',true).order('full_name'),
    supabase.from('attendance').select('*').gte('attendance_date',from).lte('attendance_date',to).order('attendance_date',{ascending:false}),
    supabase.from('daily_reports').select('*').gte('report_date',from).lte('report_date',to).order('report_date',{ascending:false}),
    supabase.from('work_calendar').select('work_date').eq('is_workday',true).gte('work_date',from).lte('work_date',to).order('work_date')
   ]);if(e.error||a.error||r.error||c.error)throw new Error();setEmployees((e.data??[]) as Employee[]);setAttendance((a.data??[]) as Attendance[]);setReports((r.data??[]) as DailyReport[]);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});setWorkdays((c.data??[]).map(x=>x.work_date).filter(x=>x<today));await loadResets();
 }catch{setMessage('Data admin belum dapat dimuat.')}finally{setBusy(false)}};
 useEffect(()=>{if(Platform.OS==='web')void load();else setAllowed(false)},[]);
 const summary=useMemo<Summary[]>(()=>employees.map(e=>{const rows=attendance.filter(a=>a.employee_id===e.id);const count=(x:string)=>rows.filter(a=>a.status===x).length;const filled=new Set(rows.map(a=>a.attendance_date));return{...e,hadir:rows.filter(a=>!!a.check_in).length,izin:count('Izin'),sakit:count('Sakit'),cuti:count('Cuti'),dinas:count('Dinas Luar'),tanpa:workdays.filter(date=>!filled.has(date)).length,total:workdays.length}}),[employees,attendance,workdays]);
 if(Platform.OS!=='web')return <View style={s.center}><Text>Dashboard admin hanya tersedia melalui web.</Text></View>;
 if(allowed===false)return <View style={s.center}><Text style={s.denied}>Akses ditolak. Halaman ini khusus admin.</Text></View>;
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>Dashboard Admin</Text><Text style={s.sub}>Rekap seluruh pegawai · SDN Kalibaru 3</Text>
  {(yearOpen||monthOpen)&&<Pressable style={s.dropdownBackdrop} onPress={closeDropdowns}/>}<View style={s.controls}><View style={s.selectWrap}><Pressable style={s.select} onPress={()=>{setYearOpen(!yearOpen);setMonthOpen(false)}}><Text>{selectedYear}</Text><Text>⌄</Text></Pressable>{yearOpen&&<ScrollView style={s.menu} nestedScrollEnabled showsVerticalScrollIndicator>{years.map(year=><Pressable key={year} style={s.option} onPress={()=>chooseYear(year)}><Text>{year}</Text></Pressable>)}</ScrollView>}</View><Text style={s.separator}>|</Text><View style={[s.selectWrap,s.monthSelect]}><Pressable style={s.select} onPress={()=>{setMonthOpen(!monthOpen);setYearOpen(false)}}><Text>{MONTHS[selectedMonth-1]}</Text><Text>⌄</Text></Pressable>{monthOpen&&<ScrollView style={s.menu} nestedScrollEnabled showsVerticalScrollIndicator>{MONTHS.map((label,index)=><Pressable key={label} style={s.option} onPress={()=>chooseMonth(index+1)}><Text>{label}</Text></Pressable>)}</ScrollView>}</View><Pressable style={s.button} disabled={busy} onPress={load}><Text style={s.buttonText}>{busy?'Memuat…':'Tampilkan'}</Text></Pressable><Pressable style={[s.button,s.syncButton]} disabled={busy} onPress={sync}><Text style={s.buttonText}>Sinkronkan Spreadsheet</Text></Pressable><Pressable style={[s.button,s.printButton]} disabled={busy} onPress={printAllMonthlyRecap}><Text style={s.buttonText}>Cetak Rekap Semua Pegawai</Text></Pressable></View>{!!message&&<Text>{message}</Text>}
  <Text style={s.heading}>Permintaan Reset Password ({resets.length})</Text>{resets.length===0?<Text style={s.muted}>Tidak ada permintaan reset.</Text>:resets.map(request=><View key={request.id} style={s.resetCard}><View style={s.resetInfo}><Text style={s.cardTitle}>{request.login_code}</Text><Text style={s.muted}>Diajukan {new Date(request.requested_at).toLocaleString('id-ID')}</Text></View><View style={s.resetActions}><Pressable style={s.dismissButton} disabled={busy} onPress={()=>dismissReset(request.id)} accessibilityLabel="Abaikan permintaan reset"><Text style={s.dismissText}>×</Text></Pressable><Pressable style={s.resetButton} disabled={busy} onPress={()=>approveReset(request.id)}><Text style={s.buttonText}>Buat Password Sementara</Text></Pressable></View></View>)}
  <Text style={s.heading}>Rekap Bulanan</Text><ScrollView horizontal><View>
   <View style={[s.row,s.header]}><Text style={[s.cell,s.name,s.headText]}>Nama</Text>{['Jabatan','Absen Masuk','Izin','Sakit','Cuti','Dinas Luar','Tanpa Ket.','Hari Kerja'].map(x=><Text key={x} style={[s.cell,s.headText]}>{x}</Text>)}</View>
   {summary.map(x=><View key={x.id} style={s.row}><Text style={[s.cell,s.name]}>{x.full_name}</Text><Text style={s.cell}>{x.position}</Text>{[x.hadir,x.izin,x.sakit,x.cuti,x.dinas,x.tanpa,x.total].map((n,i)=><Text key={i} style={s.cell}>{n}</Text>)}</View>)}
  </View></ScrollView>
  <Text style={s.heading}>Laporan Harian ({reports.length})</Text>{reports.map(r=>{const e=employees.find(x=>x.id===r.employee_id);return <View key={r.id} style={s.card}><Text style={s.cardTitle}>{r.report_date} · {e?.full_name??'Pegawai'}</Text><Text>{r.activity}</Text>{!!r.result&&<Text style={s.muted}>Hasil: {r.result}</Text>}</View>})}
 </ScrollView>;
}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]!))}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f7faf8'},content:{position:'relative',padding:28,paddingTop:50,paddingBottom:60,maxWidth:1200,width:'100%',alignSelf:'center'},dropdownBackdrop:{position:'absolute',top:0,left:0,right:0,bottom:0,zIndex:5},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},denied:{color:'#b42318',fontWeight:'800'},title:{fontSize:30,fontWeight:'900',color:'#18794e'},sub:{marginTop:5,marginBottom:20,color:'#5f6d64'},controls:{flexDirection:'row',flexWrap:'wrap',alignItems:'flex-start',gap:10,marginBottom:18,zIndex:10},selectWrap:{width:105,position:'relative',zIndex:20},monthSelect:{width:150},select:{height:44,borderWidth:1,borderColor:'#cfd8d3',backgroundColor:'#fff',borderRadius:10,paddingHorizontal:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},separator:{paddingTop:11,fontWeight:'800',color:'#647168'},menu:{position:'absolute',top:48,left:0,right:0,maxHeight:260,backgroundColor:'#fff',borderWidth:1,borderColor:'#cfd8d3',borderRadius:10,zIndex:30,boxShadow:'0 8px 22px rgba(0,0,0,.14)'},option:{paddingHorizontal:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#edf1ee'},button:{backgroundColor:'#18794e',paddingHorizontal:18,paddingVertical:12,justifyContent:'center',borderRadius:10},syncButton:{backgroundColor:'#2563a6'},printButton:{backgroundColor:'#7a4e12'},buttonText:{color:'#fff',fontWeight:'800'},heading:{fontSize:21,fontWeight:'800',marginTop:20,marginBottom:10},resetCard:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e0e9e3',padding:14,borderRadius:12,marginBottom:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'},resetInfo:{flexGrow:1},resetActions:{flexDirection:'row',alignItems:'center',gap:8},dismissButton:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:'#d0d8d3',backgroundColor:'#f5f7f6',alignItems:'center',justifyContent:'center'},dismissText:{fontSize:24,lineHeight:26,color:'#7a271a'},resetButton:{backgroundColor:'#b54708',padding:11,borderRadius:9},row:{flexDirection:'row',backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:'#e2e9e4'},header:{backgroundColor:'#e4ece7'},cell:{width:115,padding:11,textAlign:'center'},name:{width:230,textAlign:'left',fontWeight:'600'},headText:{fontWeight:'800'},card:{backgroundColor:'#fff',padding:15,borderRadius:12,borderWidth:1,borderColor:'#e0e9e3',marginBottom:8,gap:5},cardTitle:{fontWeight:'800',color:'#18794e'},muted:{color:'#647168'}});
