import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import DateTimePicker, { DateTimePickerEvent } from '@react-native-community/datetimepicker';
import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system/legacy';
import KeyboardScroll from '@/components/KeyboardScroll';
import { notifyRecapDownloadComplete } from '@/lib/attendanceNotifications';
import { currentEmployee, ownAttendance, ownReportsRange, ownWorkPreference } from '@/lib/data';
import type { Attendance, DailyReport, Employee, WorkPattern } from '@/lib/types';

const todayMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit'}).format(new Date());
const monthName=(month:string)=>new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(`${month}-15T12:00:00`));
const safe=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]??char));
const range=(month:string)=>{const [year,value]=month.split('-').map(Number);const last=new Date(year,value,0).getDate();return{from:`${month}-01`,to:`${month}-${String(last).padStart(2,'0')}`,last}};

export default function PersonalMonthlyRecap(){
 const[month,setMonth]=useState(todayMonth());const[employee,setEmployee]=useState<Employee|null>(null);const[attendance,setAttendance]=useState<Attendance[]>([]);const[reports,setReports]=useState<DailyReport[]>([]);const[workPattern,setWorkPattern]=useState<WorkPattern>('Opsi 1');const[picker,setPicker]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const load=async(selected=month)=>{setBusy(true);setMessage('');try{const{from,to}=range(selected);const[e,a,r,p]=await Promise.all([currentEmployee(),ownAttendance(from,to),ownReportsRange(from,to),ownWorkPreference()]);setEmployee(e);setAttendance(a);setReports(r);setWorkPattern(p.workPattern)}catch{setMessage('Rekap bulanan belum dapat dimuat.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const chooseMonth=(_event:DateTimePickerEvent,value?:Date)=>{setPicker(false);if(!value)return;const selected=`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}`;setMonth(selected);void load(selected)};
 const html=()=>{if(!employee)return'';const{last}=range(month);const attendanceMap=new Map(attendance.map(row=>[row.attendance_date,row]));const reportMap=new Map(reports.map(row=>[row.report_date,row]));const rows=Array.from({length:last},(_,index)=>{const date=`${month}-${String(index+1).padStart(2,'0')}`;const day=new Date(`${date}T12:00:00`);const sunday=day.getDay()===0;const saturdayOff=workPattern==='Opsi 1'&&day.getDay()===6;const a=attendanceMap.get(date);const report=reportMap.get(date);let activity=sunday?'Hari Minggu':saturdayOff?'Sabtu (libur)':report?.activity??'';if(!activity&&a&&['Izin','Sakit','Cuti','Dinas Luar'].includes(a.status))activity=`Pengajuan Tidak Hadir: ${a.status}`;return`<tr><td>${safe(new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'}).format(day))}</td><td>${safe(a?.check_in?.slice(0,5)??'-')}</td><td>${safe(a?.check_out?.slice(0,5)??'-')}</td><td>${safe(activity||'-')}</td></tr>`}).join('');return`<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:16mm}body{font-family:Arial,sans-serif;color:#17231c;font-size:11px}h1{text-align:center;font-size:18px;margin:0 0 3px;text-transform:uppercase}h2{text-align:center;font-size:14px;margin:0 0 18px}.meta{margin-bottom:14px}.meta td{padding:2px 8px 2px 0}.recap{border-collapse:collapse;width:100%;table-layout:fixed}.recap th,.recap td{border:1px solid #66736b;padding:6px;vertical-align:top}.recap th{background:#dff0e4;color:#124d32}.recap th:nth-child(1){width:19%}.recap th:nth-child(2),.recap th:nth-child(3){width:14%}.recap td:nth-child(1),.recap td:nth-child(2),.recap td:nth-child(3){text-align:center}.footer{margin-top:10px;color:#647168;font-size:9px;text-align:right}</style></head><body><h1>Rekap Absensi PPPK Paruh Waktu</h1><h2>${safe(employee.unit_name)}</h2><table class="meta"><tr><td>Bulan</td><td>: <b>${safe(monthName(month))}</b></td></tr><tr><td>Nama Pegawai</td><td>: <b>${safe(employee.full_name)}</b></td></tr><tr><td>NI PPPK</td><td>: <b>${safe(employee.ni_pppk||'-')}</b></td></tr><tr><td>Jabatan</td><td>: <b>${safe(employee.position)}</b></td></tr><tr><td>Unit Dinas</td><td>: <b>${safe(employee.unit_name)}</b></td></tr></table><table class="recap"><thead><tr><th>Tanggal</th><th>Jam Masuk</th><th>Jam Pulang</th><th>Kegiatan</th></tr></thead><tbody>${rows}</tbody></table><div class="footer">Dicetak dari KEMOB KW</div></body></html>`};
 const print=async()=>{if(!employee)return;setBusy(true);setMessage('');try{await Print.printAsync({html:html()})}catch{setMessage('Menu cetak belum dapat dibuka.')}finally{setBusy(false)}};
 const download=async()=>{if(!employee)return;setBusy(true);setMessage('');try{const permission=await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync();if(!permission.granted){setMessage('Penyimpanan dibatalkan. Pilih folder tujuan untuk menyimpan PDF.');return}const result=await Print.printToFileAsync({html:html()});const employeeName=employee.full_name.toLowerCase().replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');const monthYear=monthName(month).toLowerCase().replace(/\s+/g,'-');const fileName=`rekap-pegawai-${employeeName}-${monthYear}.pdf`;const destination=await FileSystem.StorageAccessFramework.createFileAsync(permission.directoryUri,fileName,'application/pdf');const base64=await FileSystem.readAsStringAsync(result.uri,{encoding:FileSystem.EncodingType.Base64});await FileSystem.writeAsStringAsync(destination,base64,{encoding:FileSystem.EncodingType.Base64});await notifyRecapDownloadComplete(fileName);setMessage(`PDF berhasil disimpan sebagai ${fileName}.`)}catch{setMessage('PDF belum dapat disimpan ke perangkat.')}finally{setBusy(false)}};
 return <KeyboardScroll style={s.page} contentContainerStyle={s.content}><Text style={s.title}>Rekap Bulanan Pribadi</Text><Text style={s.info}>Pilih bulan, lalu cetak atau simpan rekap absensi pribadi dalam format PDF.</Text><Text style={s.label}>Bulan rekap</Text><Pressable style={s.monthButton} onPress={()=>setPicker(true)}><Text style={s.monthText}>{monthName(month)}</Text></Pressable>{picker&&<DateTimePicker value={new Date(`${month}-15T12:00:00`)} mode="date" display="calendar" onChange={chooseMonth}/>}<View style={s.profile}><Text style={s.name}>{employee?.full_name??'Memuat…'}</Text><Text style={s.nip}>NI PPPK: {employee?.ni_pppk||'-'}</Text><Text style={s.nip}>Unit Dinas: {employee?.unit_name??'Memuat…'}</Text></View>{!!message&&<Text style={s.message}>{message}</Text>}<Pressable disabled={busy||!employee} style={[s.button,(busy||!employee)&&s.disabled]} onPress={print}><Text style={s.buttonText}>{busy?'Memproses…':'Cetak Rekap'}</Text></Pressable><Pressable disabled={busy||!employee} style={[s.button,s.download,(busy||!employee)&&s.disabled]} onPress={download}><Text style={s.buttonText}>Download / Simpan PDF</Text></Pressable></KeyboardScroll>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f7faf8'},content:{padding:24,paddingTop:56,paddingBottom:48,gap:13},title:{fontSize:28,fontWeight:'900',color:'#18794e'},info:{lineHeight:21,color:'#526158'},label:{fontWeight:'800',marginTop:5},monthButton:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cfd8d3',borderRadius:12,padding:15},monthText:{fontSize:17,fontWeight:'800',color:'#18794e'},profile:{backgroundColor:'#e3f2e8',borderRadius:14,padding:15,gap:5},name:{fontSize:17,fontWeight:'900',color:'#174b34'},nip:{color:'#526158'},button:{backgroundColor:'#18794e',padding:15,borderRadius:12,alignItems:'center'},download:{backgroundColor:'#225a91'},buttonText:{color:'#fff',fontWeight:'800'},disabled:{opacity:.5},message:{color:'#35453b',lineHeight:20}});
