import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import DateTimePicker, { DateTimePickerEvent } from '@react-native-community/datetimepicker';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import KeyboardScroll from '@/components/KeyboardScroll';
import { notifyRecapDownloadComplete } from '@/lib/attendanceNotifications';
import { createPersonalRecapPdf } from '@/lib/personalRecapPdf';
import { currentEmployee, ownAttendance, ownReportsRange, ownWorkPreference } from '@/lib/data';
import type { Attendance, DailyReport, Employee, WorkPattern } from '@/lib/types';

const todayMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit'}).format(new Date());
const monthName=(month:string)=>new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(`${month}-15T12:00:00`));
const range=(month:string)=>{const [year,value]=month.split('-').map(Number);const last=new Date(year,value,0).getDate();return{from:`${month}-01`,to:`${month}-${String(last).padStart(2,'0')}`,last}};

export default function PersonalMonthlyRecap(){
 const[month,setMonth]=useState(todayMonth());const[employee,setEmployee]=useState<Employee|null>(null);const[attendance,setAttendance]=useState<Attendance[]>([]);const[reports,setReports]=useState<DailyReport[]>([]);const[workPattern,setWorkPattern]=useState<WorkPattern>('Opsi 1');const[picker,setPicker]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const load=async(selected=month)=>{setBusy(true);setMessage('');try{const{from,to}=range(selected);const[e,a,r,p]=await Promise.all([currentEmployee(),ownAttendance(from,to),ownReportsRange(from,to),ownWorkPreference()]);setEmployee(e);setAttendance(a);setReports(r);setWorkPattern(p.workPattern)}catch{setMessage('Rekap bulanan belum dapat dimuat.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const chooseMonth=(_event:DateTimePickerEvent,value?:Date)=>{setPicker(false);if(!value)return;const selected=`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}`;setMonth(selected);void load(selected)};
 const makePdf=()=>createPersonalRecapPdf({month,employee:employee!,attendance,reports,workPattern});
 const print=async()=>{if(!employee)return;setBusy(true);setMessage('Sedang membuat PDF…');try{const result=await makePdf();const available=await Sharing.isAvailableAsync();if(!available){setMessage('Perangkat ini tidak menyediakan menu untuk membuka atau mencetak PDF. Gunakan tombol Simpan PDF.');return}await Sharing.shareAsync(result.uri,{mimeType:'application/pdf',UTI:'com.adobe.pdf',dialogTitle:'Buka atau cetak rekap'});setMessage('PDF berhasil dibuat. Pilih layanan cetak atau aplikasi PDF pada menu yang muncul.')}catch(error){console.error('personal-recap-pdf',error);setMessage('PDF belum dapat dibuat. Coba kembali atau gunakan tombol Simpan PDF.')}finally{setBusy(false)}};
 const download=async()=>{if(!employee)return;setBusy(true);setMessage('');try{const permission=await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync();if(!permission.granted){setMessage('Penyimpanan dibatalkan. Pilih folder tujuan untuk menyimpan PDF.');return}setMessage('Sedang membuat PDF…');const result=await makePdf();const destination=await FileSystem.StorageAccessFramework.createFileAsync(permission.directoryUri,result.fileName,'application/pdf');await FileSystem.writeAsStringAsync(destination,result.base64,{encoding:FileSystem.EncodingType.Base64});await notifyRecapDownloadComplete(result.fileName);setMessage(`PDF berhasil disimpan sebagai ${result.fileName}.`)}catch(error){console.error('personal-recap-download',error);setMessage('PDF belum dapat disimpan ke perangkat.')}finally{setBusy(false)}};
 return <KeyboardScroll style={s.page} contentContainerStyle={s.content}><Text style={s.title}>Rekap Bulanan Pribadi</Text><Text style={s.info}>Pilih bulan, lalu buka, cetak, bagikan, atau simpan rekap absensi pribadi dalam format PDF.</Text><Text style={s.label}>Bulan rekap</Text><Pressable style={s.monthButton} onPress={()=>setPicker(true)}><Text style={s.monthText}>{monthName(month)}</Text></Pressable>{picker&&<DateTimePicker value={new Date(`${month}-15T12:00:00`)} mode="date" display="calendar" onChange={chooseMonth}/>}<View style={s.profile}><Text style={s.name}>{employee?.full_name??'Memuat…'}</Text><Text style={s.nip}>NI PPPK: {employee?.ni_pppk||'-'}</Text><Text style={s.nip}>Unit Dinas: {employee?.unit_name??'Memuat…'}</Text></View>{!!message&&<Text style={s.message}>{message}</Text>}<Pressable disabled={busy||!employee} style={[s.button,(busy||!employee)&&s.disabled]} onPress={print}><Text style={s.buttonText}>{busy?'Memproses…':'Buka / Cetak PDF'}</Text></Pressable><Pressable disabled={busy||!employee} style={[s.button,s.download,(busy||!employee)&&s.disabled]} onPress={download}><Text style={s.buttonText}>Download / Simpan PDF</Text></Pressable></KeyboardScroll>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f7faf8'},content:{padding:24,paddingTop:56,paddingBottom:48,gap:13},title:{fontSize:28,fontWeight:'900',color:'#18794e'},info:{lineHeight:21,color:'#526158'},label:{fontWeight:'800',marginTop:5},monthButton:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cfd8d3',borderRadius:12,padding:15},monthText:{fontSize:17,fontWeight:'800',color:'#18794e'},profile:{backgroundColor:'#e3f2e8',borderRadius:14,padding:15,gap:5},name:{fontSize:17,fontWeight:'900',color:'#174b34'},nip:{color:'#526158'},button:{backgroundColor:'#18794e',padding:15,borderRadius:12,alignItems:'center'},download:{backgroundColor:'#225a91'},buttonText:{color:'#fff',fontWeight:'800'},disabled:{opacity:.5},message:{color:'#35453b',lineHeight:20}});
