import { ScrollView, StyleSheet, Text, View } from 'react-native';

const Section=({title,children}:{title:string;children:React.ReactNode})=><View style={s.section}><Text style={s.heading}>{title}</Text><Text style={s.body}>{children}</Text></View>;
export default function Privacy(){
  return <ScrollView style={s.page} contentContainerStyle={s.content}>
    <Text style={s.title}>Kebijakan Privasi</Text>
    <Text style={s.updated}>KEMOB KW · SDN Kalibaru 3 · diperbarui 27 Agustus 2026</Text>
    <Section title="Tentang aplikasi">KEMOB KW adalah aplikasi internal untuk absensi dan laporan kegiatan PPPK Paruh Waktu SDN Kalibaru 3. Aplikasi ini bukan aplikasi resmi KMOB dan tidak berafiliasi dengan pengelola KMOB.</Section>
    <Section title="Data yang diperlukan">Aplikasi memproses nama, jabatan, NI PPPK atau kode pegawai, identitas akun internal, pilihan shift, tanggal dan waktu absensi, status kehadiran, catatan, serta laporan kegiatan harian. Data ini diperlukan agar fungsi absensi, koreksi, rekap, dan pelaporan dapat digunakan.</Section>
    <Section title="Tujuan penggunaan">Data digunakan hanya untuk pencatatan kehadiran, pemeriksaan kelengkapan absensi, penyusunan rekap bulanan, dan laporan administrasi kepegawaian sekolah.</Section>
    <Section title="Akses data">Pegawai hanya dapat melihat dan mengubah datanya sendiri. Admin yang ditunjuk sekolah dapat mengelola serta melihat rekap semua pegawai. Saat ini admin adalah Dovy Wahyu Widhiarta dan Rosadi, SE.</Section>
    <Section title="Tidak diperjualbelikan atau disebarluaskan">Pengelola tidak menjual, menyewakan, memublikasikan, atau membagikan data pegawai kepada pihak di luar kebutuhan administrasi SDN Kalibaru 3. Penyampaian data hanya dilakukan apabila diperlukan untuk administrasi resmi, atas persetujuan atau kewenangan sekolah, atau diwajibkan oleh ketentuan hukum.</Section>
    <Section title="Penyimpanan dan keamanan">Data utama disimpan pada Supabase dan rekap disinkronkan ke Google Spreadsheet sekolah. Akses dibatasi melalui akun, kata sandi, kebijakan keamanan per baris, koneksi terenkripsi, dan hak akses admin. Kunci layanan disimpan sebagai rahasia server dan tidak ditanamkan di APK.</Section>
    <Section title="Data perangkat yang tidak diambil">Aplikasi tidak meminta atau merekam lokasi/GPS, kontak, SMS, riwayat telepon, IMEI, mikrofon, kamera, foto, video, berkas pribadi, Bluetooth, maupun data periklanan perangkat. Aplikasi hanya menggunakan koneksi internet untuk login dan pertukaran data absensi.</Section>
    <Section title="Catatan teknis layanan">Supabase dan Google dapat mencatat informasi teknis yang diperlukan untuk keamanan dan pengoperasian layanan, seperti waktu permintaan, status koneksi, serta peristiwa login. Catatan teknis tersebut tidak memberi aplikasi akses ke kontak, foto, pesan, atau isi pribadi lain di perangkat.</Section>
    <Section title="Tanggung jawab pengguna">Pengguna tidak boleh memasukkan kata sandi, data sensitif siswa, rincian kesehatan yang tidak diperlukan, atau informasi rahasia lain pada kolom catatan dan laporan harian. Pengguna wajib menjaga kata sandi akun dan segera melapor kepada admin apabila menduga akun digunakan pihak lain.</Section>
    <Section title="Penyimpanan dan penghapusan">Data disimpan selama masih diperlukan untuk administrasi kepegawaian sekolah. Permintaan koreksi, salinan, atau penghapusan dapat diajukan kepada admin. Data yang wajib dipertahankan berdasarkan kebutuhan administrasi atau ketentuan yang berlaku tidak akan dihapus sebelum masa penyimpanannya berakhir.</Section>
    <Section title="Hak pengguna">Pegawai dapat melihat dan memperbaiki data absensinya. Permintaan koreksi akun, akses data, atau penghapusan diajukan kepada admin sekolah. Data yang wajib dipertahankan untuk kepentingan administrasi akan dijelaskan saat permintaan diproses.</Section>
    <Section title="Perubahan kebijakan">Perubahan kebijakan yang memengaruhi cara data diproses akan dicantumkan pada halaman ini sebelum atau saat versi aplikasi terbaru digunakan.</Section>
    <Section title="Kontak pengelola">SDN Kalibaru 3, Kecamatan Cilodong, Kota Depok. Email: sdnkalibaru34@gmail.com.</Section>
  </ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f7faf8'},content:{padding:24,paddingTop:64,paddingBottom:48,maxWidth:760,width:'100%',alignSelf:'center'},title:{fontSize:30,fontWeight:'900',color:'#18794e'},updated:{marginTop:8,marginBottom:24,color:'#66736b'},section:{backgroundColor:'#fff',padding:18,borderRadius:14,marginBottom:12,borderWidth:1,borderColor:'#e0e9e3'},heading:{fontSize:17,fontWeight:'800',marginBottom:7},body:{lineHeight:22,color:'#35453b'}});
